### ISSUE TITLE
Document usable fields

### ISSUE THREAD

**Issue by fschutt** [volks73/cargo-wix#50]
If you support a seperate `[wix]` section - what keys / values are valid? For example, it would be nice, not to add the `main.wxs` into source control. It would be great if settings (app icon, banner, help / documentation link, etc.) could be set via the `Cargo.toml` file instead of the `main.wxs` file:

Also, it would be great, if you could support a "nice name". Cargo will complain if you capitalize the package name (which is OK), but for a user it's often more friendly to have a capitalized name

I.e. something like this:

```toml
[package]
name = "something"

[package.metadata.wix]
nice-name = "Something Editor Pro"
icon = "assets/main.ico"
help = "http://company.com/support"
install-banner-picture = "assets/Banner.bmp"
install-dialog-picture = "assets/Dialog.bmp"
```

It would be great if this could be done directly in the `Cargo.toml` file, so that the `main.wxs` file doesn't need to be checked into version control. If something like this is already possible, it would be good to have some documentation on which fields / keys are valid.
